version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*webpack*"
          - "*loader*"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*eslint*"
          - "*webpack*"
          - "*loader*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
