name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build extension
      run: npm run build
    
    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ../extension.zip *
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: extension.zip
        generate_release_notes: true
        draft: true
